name: vaccine_for_the_people
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  auto_size_text: ^3.0.0
  dartz: ^0.10.0
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.2.0
  lottie: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  syncfusion_flutter_charts: ^19.4.38
  syncfusion_flutter_maps: ^19.2.57-beta
  data_table_2: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - vietnam1.json
    - assets/vietnam1.json
    - vietnam2.json
    - assets/vietnam2.json
    - vietnam3.json
    - assets/vietnam3.json
    - assets/images/
    - assets/province.json